name: Test My Router App

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Get my code
      uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    
    - name: Install stuff
      run: |
        pip install -r requirements.txt
    
    - name: Run my tests
      run: pytest tests/ -v

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Fake deploy
      run: |
        echo "Deploying my router dashboard..."
        sleep 3
        echo "✅ App deployed successfully!"